FROM maven:3.9.9
WORKDIR /app

# Copy only pom.xml first for dependency caching
COPY pom.xml .

# Copy source code
COPY . .

# Expose port
EXPOSE 8080

# Run app with environment variables from docker-compose
CMD ["mvn", "spring-boot:run"]
