@template.layout.main(
    title = "Welcome",
    content = @`
    <%-- TODO this needs to be made better --%>
    <div style="display: flex; justify-content: center; align-items: center; width: 100%; height: 100%; flex-direction: column;">
        <div>
            <h2>Welcome to JCS!</h2>
            <p>To ask a question or start to start answering, please make an account.</p>
            <p>Otherwise, you may search previously asked questions!</p>
        </div>
    </div>
    `
)